### ISSUE TITLE
Modal windows

### ISSUE THREAD

**Issue by codepotato** [aaronrussell-x/jquery-simply-countable#2]
I find that this doesn't work within model windows and i have a suspicion its todo with the fact you're not using the jquery .live() function as some modals alter DOM objects after page load.

**Comment by aaronrussell-x** [comment]
Are you populating the modal window via ajax?

**Comment by codepotato** [comment]
No, the modal window is simply opening a hidden div on the page.

**Comment by codepotato** [comment]
It's slightly odd, as it'll show the value in the counter div, but won't update when you type. I'm using the easy framework www.easyframework.com with your script.

**Comment by aaronrussell-x** [comment]
I'm not confident switching to the live method will work in this instance. Can you try it?

Simply change line 101 of my plugin to:

```
countable.live('keyup', countCheck);
```

Let me know how it goes.

**Comment by codepotato** [comment]
hmm, doesn't solve it. :( I'm @cssgareth on twitter btw, been following you for a while now :)

**Comment by aaronrussell-x** [comment]
Didn't think it would. It sounds like the modal window is "cloning" the dom elements - essentially creating new copies of them, leaving the `simplyCountable` method attached to the original hidden elements.

Does the modal plugin have any callback methods? If so, you should be able to call `simplyCountable` after the modal window has opened?
