### ISSUE TITLE
Use GitHub Pages for the Demo

### ISSUE THREAD

**Issue by chrisjacob** [aaronrussell-x/jquery-simply-countable#5]
May I suggest you add a gh-pages branch to host the demo ( free on GitHub Pages ).

http://pages.github.com/

Thanks for this excellent plugin BTW!

**Comment by aaronrussell-x** [comment]
Thanks for the suggestion Chris. There are plans afoot to host all my projects properly on my own site, which will include demo's etc.

I'm currently trying to work out the best way of achieving this, using git etc, to automate as much as possible. It's taking a while, but all I can say at this point is it's coming ;)

Thanks for the suggestion. Going to close this ticket.
